services:
  mongo:
    image: mongo:7
    container_name: mongo-airports
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis-pop:
    image: redis:7
    container_name: redis-pop-airports
    ports:
      - "6379:6379"

  redis-geo:
    image: redis:7
    container_name: redis-geo-airports
    ports:
      - "6380:6379"

  backend:
    build: ./backend
    container_name: backend-airports
    ports:
      - "3000:3000"
    depends_on:
      - mongo
      - redis-pop
      - redis-geo
    environment:
      - MONGO_URI=mongodb://mongo:27017/airport_db
      - REDIS_GEO_URL=redis://redis-geo:6379
      - REDIS_POP_URL=redis://redis-pop:6379
      - PORT=3000

  frontend:
    build: ./frontend
    container_name: frontend-airports
    ports:
      - "5173:5173"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://localhost:3000

volumes:
  mongo_data:
